[package]
name = "bevy_shape_draw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version= "0.9"}
bevy_input = { version = "0.9", features = ["serialize"] }
bevy_mod_raycast = "0.7"